/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:255bf2db-cd73-4a0a-b2ce-e86a6544f1ae",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_9zE0WYRgz",
    "aws_user_pools_web_client_id": "3phaff932eemsc7dekhs2dlqe7",
    "oauth": {}
};


export default awsmobile;
